apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREEzTVRndwpOakl5TkRCYUZ3MDBOREEzTVRnd05qSXlOREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMUFyRDJ5dzE5SHpNVWs3TW1jdUVyelE3V1ZhSk1MWEhVWDV6VHNiYjVRaU9lS2IyWQo4MkxxUzhMNXZvTDc4SzFCT1VKK0VWdUhUY2dhV0pRR055VjZFai9ISHVSeitxMTVlL2dKQU13aGdHUXlkYlc3CnJTS3ZSK1M2MUVsb013TzVFOGFINjdXdnlucGFmZXJCYnZ0SytxYS9adXVWdWlhSTdNQ3NnbmN1SkMxSXdzYVoKR0xLcGhiN0FVanZORXIzcEdYMGZUVXcwekwrOUZNTlVBZTVOa25KSVJvL3lRQzAwQVc0TjNKcDJqNEl5MnVzaQowTSt6V01Gay9NeUtZT2ZuU1hRK3ptTkZNOGJYZmhEZkNsTjJEYjhJS3B3OVpvTWlZK1FBQ0tvSDZrWm43Y1lYCjlIK3p4cUNNdjJPdHlJM2JDQzhaNDMrQ2JtZGw0NkJkNDJYckFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRZZjVONEN6M1Q2L0VxUFBwdQoxWGVZVHRXNkxqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFMRVozc1ZrblRhaFFBUXlIaUtIaFdtNWVsY2V0Ck1BVmhyTWhxcWRvcXZaZVN5NDI2L1MrY0JBblY1M3JHQnZiSzltbDRjR25jOG9nc0ZCUDlvNFlqWXlVNFVXMjAKdFFIb2Irc1RHalhkblEyUWl2bEk1SC9mSzFJak94dHJtcG5ybnVETWxKUkcweUUrZ3hyTmE2eHNleWxQRC9QTAo3TXhXT3lyYmFSRm5EeGlERHhqWCtvSmErdzNKM1BzaklNOHIzaEsvR2VXZ2JUZCtqL2VVK2hUNThPSW05WTM4Cm9mcHBvK2w5UUJYTC9sY0NuUHRNN1pjRGo5eSszays2MDY0Q0t0Sk8rbm9abjVBTFVVLzlXK2psZW5nWEZJWHAKRExnSEdRTHZnYTVZck0zdUsyQUZPaGptMmp0RkZ5eFJmdlg3UWs1RWtNcTFuUVdWVkIwV25SRitrZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0fc55435-97be-40d0-8ea0-ad23af8c2ee6.k8s.ondigitalocean.com
  name: do-blr1-magento-avoirchic-cluster
contexts:
- context:
    cluster: do-blr1-magento-avoirchic-cluster
    user: do-blr1-magento-avoirchic-cluster-admin
  name: do-blr1-magento-avoirchic-cluster
current-context: do-blr1-magento-avoirchic-cluster
kind: Config
preferences: {}
users:
- name: do-blr1-magento-avoirchic-cluster-admin
  user:
    token: dop_v1_95f757ee90243d28164348dae7b1dba71465493058c5b7e8736a67545be31c26
